cratePipeline(
    name: 'arm-gic',
    project: 'arm-firmware-crates',
    features: ['fakes'],

    gerrit: [
        host: params.GERRIT_HOST,
        project: params.GERRIT_PROJECT,
        refspec: params.GERRIT_REFSPEC,
        branch: params.GERRIT_BRANCH,
    ],
)
