cratePipeline(
    name: 'tf-firmware-handoff',
    project: 'shared',

    gerrit: [
        host: params.GERRIT_HOST,
        project: params.GERRIT_PROJECT,
        refspec: params.GERRIT_REFSPEC,
        branch: params.GERRIT_BRANCH,
    ],
)
