cratePipeline(
    name: 'arm-fvp-base-pac',
    project: 'arm-firmware-crates',

    gerrit: [
        host: params.GERRIT_HOST,
        project: params.GERRIT_PROJECT,
        refspec: params.GERRIT_REFSPEC,
        branch: params.GERRIT_BRANCH,
    ],
)
