pipeline {
    agent {
        label 'docker-amd64-tf-a-jammy'
    }

    parameters {
        string(
            name: 'URL',
            defaultValue: 'https://review.trustedfirmware.org/shared/transfer-list-library',
            description: 'Repository URL.')

        string(
            name: 'REFSPEC',
            defaultValue: '+refs/heads/main',
            description: 'Git refspec used when fetching.')

        string(
            name: 'REFNAME',
            defaultValue: 'FETCH_HEAD',
            description: 'Git refname of the first commit to check.')

        string(
            name: 'BASE_REFSPEC',
            defaultValue: '+refs/heads/main',
            description: 'Git refspec of the parent of the last commit to check.')

        string(
            name: 'BASE_REFNAME',
            defaultValue: 'FETCH_HEAD',
            description: 'Git refname of the parent of the first last commit to check.')
    }

   stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[ name: params.REFNAME ]],
                    // TODO: shallow clone
                    extensions: [ cloneOption(honorRefspec: true) ],
                    userRemoteConfigs: [
                        [ url: params.URL, refspec: "${params.BASE_REFSPEC} ${params.REFSPEC}" ]
                    ]
                ])

                sh "git show --no-patch HEAD" // TODO: remove me after testing
            }
        }

        stage('Install') {
            steps {
                dir('tlc') {
                    sh 'poetry install --with dev'
                }
            }
        }

        stage('Codestyle') {
            parallel {
                stage('Style') {
                    steps {
                        dir('tlc') {
                            sh 'poetry run isort --diff --check-only --settings-path pyproject.toml ./'
                            sh 'poetry run black --diff --check --config pyproject.toml ./'
                            sh 'poetry run darglint --verbosity 2 tlc tests'
                        }
                    }
                }

                stage('Static Checks') {
                    steps {
                        dir('tlc') {
                            sh 'poetry run mypy --config-file pyproject.toml ./'
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('tlc') {
                    sh "poetry run pytest -c pyproject.toml --cov-report=xml --cov=tlc tests/"

                    recordCoverage(
                        tools: [[parser: 'COBERTURA', pattern: "coverage.xml"]],
                        id: 'cobertura', name: 'Code Coverage',
                        sourceCodeRetention: 'EVERY_BUILD',
                    )
                }
            }
      }

        stage('Build') {
            steps {
                dir('tlc') {
                    sh 'poetry build'
                    archiveArtifacts artifacts: 'dist/**', fingerprint: true
                }
            }
        }
    }
}
