gerritPipeline(
    builderJob: 'tf-a-lts2.14-builder',
    builderNode: 'docker-amd64-tf-a-lts2.14-jammy',

    commitLint: true,

    gerrit: [
        project: params.GERRIT_PROJECT,
        refspec: params.GERRIT_REFSPEC,
        branch: params.GERRIT_BRANCH,
        revision: params.GERRIT_PATCHSET_REVISION,
    ],

    tfa: [project: params.GERRIT_PROJECT, refspec: params.GERRIT_REFSPEC],
    rfa: [project: 'RF-A/rusted-firmware-a', refspec: 'main'],

    tfut: [project: 'TF-A/tf-a-unit-tests', refspec: 'main'],
    tftf: [project: 'TF-A/tf-a-tests', refspec: 'lts-v2.14'],

    tfmTests: [project: 'TF-M/tf-m-tests', refspec: '3041b858639c85d9541c37fcbd1b42d3d0f03c79'],
    tfmExtras: [project: 'TF-M/tf-m-extras', refspec: '6edb83b21cae8ebbc3c3c219ea34d41ca0cc2bf1'],

    hafnium: [project: 'hafnium/hafnium', refspec: 'lts-v2.14'],
    rmm: [project: 'TF-RMM/tf-rmm', refspec: 'tf-rmm-v0.8.0'],

    ciScripts: [project: 'ci/tf-a-ci-scripts', refspec: 'master'],
    ciScriptsTestPrefix: 'tf-a-lts-v2.14',

    mbedtlsUrl: 'https://github.com/Mbed-TLS/mbedtls/archive/mbedtls-3.6.5.tar.gz',
)
