gerritPipeline(
    builderJob: 'tf-a-lts2.8-builder',
    builderNode: 'docker-amd64-tf-a-lts2.8-jammy',

    commitLint: true,

    gerrit: [
        project: params.GERRIT_PROJECT,
        refspec: params.GERRIT_REFSPEC,
        branch: params.GERRIT_BRANCH,
        revision: params.GERRIT_PATCHSET_REVISION,
    ],

    tfa: [project: params.GERRIT_PROJECT, refspec: params.GERRIT_REFSPEC],
    rfa: [project: 'RF-A/rusted-firmware-a', refspec: 'main'],

    tfut: [project: 'TF-A/tf-a-unit-tests', refspec: 'main'],
    tftf: [project: 'TF-A/tf-a-tests', refspec: 'lts-v2.8'],

    tfmTests: [project: 'TF-M/tf-m-tests', refspec: 'tfa_ci_dep_revision'],
    tfmExtras: [project: 'TF-M/tf-m-extras', refspec: 'tfa_ci_dep_revision'],

    hafnium: [project: 'hafnium/hafnium', refspec: 'v2.8'],
    rmm: [project: 'TF-RMM/tf-rmm', refspec: 'main'],

    ciScripts: [project: 'ci/tf-a-ci-scripts', refspec: 'master'],
    ciScriptsTestPrefix: 'tf-a-lts-v2.8',

    mbedtlsUrl: 'https://github.com/Mbed-TLS/mbedtls/archive/mbedtls-3.6.3.tar.gz',
)
